language: python
python:
  - 3.6

    # Write install command after writing requirements.md file
install: 
  - pip install -r requirements.txt
  - python -c "import nltk; nltk.download('punkt'); nltk.download('stopwords')" 
  - pip install -e

script: 
  - pwd
  - python sentimental_analysis/realworld/functional_testing.py
  - pytest
  - flake8
  - black --check --diff .
  - pylint --exit-zero .
install:
  - npm install prettier
script:
  - prettier --check .

notifications:
  email:
    recipients: 
      - mbachu@ncsu.edu
      - mnagdev@ncsu.edu
      - aagraw24@ncsu.edu
      - ppathak@ncsu.edu
      - tyeh3@ncsu.edu
    
    on_success: never
    on_failure: always
    
